export const img1 = "./images/ozo_start.png";

export const packages = [
  {
    name: "Ozo Start",
    priceRange: "25$-4999$",
    features: [
      "ROI: 1.3%",
      "Duration: 200 days",
      //"Direct Referral: 8%",
      "Binary Bonus: 10%",
      "Capping Limit: $1000",
      "Principle Returns: 100%",
      "Total Returns: 240%+100% principle amount back",
    ],
    buttonText: "Purchase",
    image: "./images/ozo starts.png",
  },
  {
    name: "Ozo Gold",
    priceRange: "$5000",
    features: [
      "ROI: 2%",
      "Duration: 100 days",
      //"Direct Referral: 8%",
      "Binary Bonus: 10%",
      "Capping Limit: $3000",
      "Principle Returns: 100%",
      "Total Returns: 200%+100% principle amount back",
    ],
    buttonText: "Purchase",
    image: "/packages/images/gold.png",
  },
  {
    name: "Ozo Prime",
    priceRange: "$10000",
    features: [
      "ROI: 2.25%",
      "Duration: 100 days",
      //"Direct Referral: 8%",
      "Binary Bonus: 10%",
      "Capping Limit: $6000",
      "Principle Returns: 100%",
      "Total Returns: 225%+100% principle amount back",
    ],
    buttonText: "Purchase",
    image: "./images/packages/prime.png",
  },
  {
    name: "Ozo Power",
    priceRange: "$5000",
    features: [
      "ROI: 2.5%",
      "Duration: 100 days",
      //"Direct Referral: 8%",
      "Binary Bonus: 10%",
      "Capping Limit: $12500",
      "Principle Returns: 100%",
      "Total Returns: 250%+100% principle amount back",
    ],
    buttonText: "Purchase",
    image: "./images/packages/power.png",
  },
  {
    name: "Ozo Striker",
    priceRange: "$2500",
    features: [
      "ROI: 1.7%",
      "Duration: 150 days",
      "Binary Bonus: 10%",
      "Capping Limit: $1500",
      "Principle Returns: 100%",
      "Total Returns: 250%+100% principle amount back",
    ],
    buttonText: "Purchase",
    image: "./images/packages/thunder.png",
  },
  // {
  //   name: "Ozo Diamond",
  //   priceRange: "$1000",
  //   features: [
  //     "ROI: 1.5%",
  //     "Duration: 150 days",
  //     //"Direct Referral: 8%",
  //     "Binary Bonus: 10%",
  //     "Capping Limit: $2000",
  //     "Principle Returns: 100%",
  //     "Total Returns: 200%+100% principle amount back",
  //   ],
  //   buttonText: "Purchase",
  //   image: "./images/ozo starts.png",
  // },

  // {
  //   name: "Ozo Growth",
  //   priceRange: "4000$-14999$",
  //   features: [
  //     "ROI: 1.4%",
  //     "Duration: 180 days",
  //     //"Direct Referral: 12%",
  //     "Binary Bonus: 10%",
  //     "Capping Limit: $2500",
  //     "Principle Returns: 100%",
  //     "Total Returns: 252%+100% principle amount back",
  //   ],
  //   buttonText: "Purchase",
  // },
  // {
  //   name: "Ozo Pro",
  //   priceRange: "15000$-34999$",
  //   features: [
  //     "ROI: 1.6%",
  //     "Duration: 160 days",
  //     //"Direct Referral: 16%",
  //     "Binary Bonus: 10%",
  //     "Capping Limit: $6400",
  //     "Principle Returns: 100%",
  //     "Total Returns: 256%+100% principle amount back",
  //   ],
  //   buttonText: "Purchase",
  // },
  // {
  //   name: "Ozo Elite",
  //   priceRange: "35000$-100000$",
  //   features: [
  //     "ROI: 1.8%",
  //     "Duration: 140 days",
  //     //"Direct Referral: 20%",
  //     "Binary Bonus: 10%",
  //     "Capping Limit: 15400$",
  //     "Principle Returns: 100%",
  //     "Total Returns: 252%+100% principle amount back",
  //   ],
  //   buttonText: "Purchase",
  // },
];
